# Site settings
title: mar.ly
email: marlified@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Marly Wilson. I'm a Ruby + Rails developer with 
  experience working across the entire stack. 
  I love challenging problems and exciting products. 
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mar.ly" # the base hostname & protocol for your site
twitter_username: mjw2_
github_username:  marly

# Build settings
markdown: kramdown

# Colletions
collections:
  recipes:
    output: true
